### ISSUE TITLE
Blog: draft/published status doesn't work. Anything that is saved is published.

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#23]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Thursday Nov 21, 2013 at 09:50 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/14_

---

**Comment by indirectlylit** [comment]
new system in place
