### ISSUE TITLE
Sticky signup banner has email box off edge of screen

### ISSUE THREAD

**Issue by jamalex** [fle-internal/fle-home#246]
Browser: Chrome on Ubuntu (running latest from @66eli77/master) 

![image](https://cloud.githubusercontent.com/assets/618416/10256755/37dbcb8c-6921-11e5-80ec-a1c5e1d2614d.png)

**Comment by 66eli77** [comment]
I also saw that on Chrome and Safari

**Comment by 66eli77** [comment]
this is fix in @jtamiace PR #247
