### ISSUE TITLE
Need way for people to sign up for FLE mailing lists

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#25]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Tuesday Dec 10, 2013 at 12:45 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/20_

---

We will soon have 2 real mailing lists -- KA Lite and LEX. Currently we don't have a way to sign up on the KA Lite site -- it would be cool to have one page on the FLE site to keep things central that we could link to from KA Lite's homepage, and from LEX's eventually.

**Comment by indirectlylit** [comment]
resolved
