### ISSUE TITLE
Enhance 404 and 500 pages to show our personality

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#26]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Tuesday Dec 10, 2013 at 13:57 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/23_

---

Idea: everyone on the team submits confused faces, we show one randomly on the 404 page along with a message.

**Comment by indirectlylit** [comment]
good idea, but closing as low priority
