### ISSUE TITLE
Add email / facebook / twitter / G+ links to "about us" profiles

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#27]
<a href="https://github.com/bcipolli"><img src="https://avatars.githubusercontent.com/u/4072455?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcipolli](https://github.com/bcipolli)**
_Wednesday Mar 05, 2014 at 18:46 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/39_

---

Now that things are data driven, it's much easier to add fields and use a more generic template.

I'd like to see all of the above linked from each person's profile!

**Comment by indirectlylit** [comment]
closing as low priority
