### ISSUE TITLE
Kolibri page - Timeline responsive design issues on FF 

### ISSUE THREAD

**Issue by radinamatic** [fle-internal/fle-home#271]
Kolibri page - Timeline responsive design issues on FF (large screen resolution - 1920px)   

a) Overlapping **April 2013** and **Oct 2015** sections
b) Images with some white space on top...??? 

![fle-responsive-ff](https://cloud.githubusercontent.com/assets/1457929/10717039/247f23f8-7b4c-11e5-862a-50064f30a9ef.png)

I only appears on first page load, and if afterwards one resizes the browser window manually or reloads the page, timeline appears correctly. 

The same issue is visible on Ubuntu 15.04 & FF (with 1366px max width), while Chrome(ium) seems not to have this problem:

![kolibri a free open source education for all learning equality - mozilla firefox_082](https://cloud.githubusercontent.com/assets/1457929/10717124/fd7dd508-7b4e-11e5-8c1c-f55d64ca2ca2.png)

c) Some elements and sections do not seem to scale appropriately to the device resolution:

![fle-responsive-ff2](https://cloud.githubusercontent.com/assets/1457929/10717103/a843dca4-7b4e-11e5-8c47-b71b1bd72f2a.png)

![fle-responsive-ff3](https://cloud.githubusercontent.com/assets/1457929/10717104/ad06b158-7b4e-11e5-8584-3abd73cbfe07.png)

**Comment by radinamatic** [comment]
Still some issues in FF on WXP & W7: http://flestaging.learningequality.org/kolibri/

![responsive5](https://cloud.githubusercontent.com/assets/1457929/10796501/b19148f8-7d9e-11e5-8ffa-81b34a7f5f96.png)

**Comment by radinamatic** [comment]
IE 11 on Windows 8: weird skewed logo:

![fle](https://cloud.githubusercontent.com/assets/1457929/10797175/b33c1aae-7da1-11e5-990d-3223a839290f.jpg)

**Comment by indirectlylit** [comment]
no longer applicable
