### ISSUE TITLE
New favicon logo for learningequality.org/?

### ISSUE THREAD

**Issue by radinamatic** [fle-internal/fle-home#272]
New favicon logo for learningequality.org/?

Not really sure if it's omitted by design or oversight...

![favicon](https://cloud.githubusercontent.com/assets/1457929/10717138/5b8fb6ca-7b4f-11e5-9fa7-1e8c111650d7.png)

**Comment by 66eli77** [comment]
fixed here #283

**Comment by radinamatic** [comment]
Looks great, Eli! :)
