### ISSUE TITLE
Indicate who are volunteers on our site

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#28]
<a href="https://github.com/bcipolli"><img src="https://avatars.githubusercontent.com/u/4072455?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcipolli](https://github.com/bcipolli)**
_Wednesday Mar 05, 2014 at 18:48 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/40_

---

As added recognition, and to focus people's attention on key points of contact, might be nice to mark volunteers clearly.

**Comment by indirectlylit** [comment]
roles are now indicated
