### ISSUE TITLE
Integrate Stripe Checkout as our donation system

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#29]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Thursday Mar 06, 2014 at 01:57 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/43_

---

https://stripe.com/checkout

Need to look into pricing, but if it's close to a better deal than paypal, we absolutely should be using this.

**Comment by indirectlylit** [comment]
this is looking good

![image](https://user-images.githubusercontent.com/2367265/32811567-623cd6a0-c955-11e7-9f6d-cbea0ffc7658.png)
