### ISSUE TITLE
Make the directions page better

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#31]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Tuesday Mar 11, 2014 at 20:54 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/51_

---

From @wangguan59 :

> Not very meaningful.
> One of my favorite direction info is d.school, http://dschool.stanford.edu/about/ Scroll down to "getting to our building".
> 
> My thoughts:
> Provide an address people can simply search in GPS. 
> provide a phone number in case they want to contact us when they get lost.
> The map is too broad. Zoom more on Google map. snapshot a school map. (Rady has pretty good map with parking info http://rady.ucsd.edu/about/rady-campus/directions/)
> Put a warren bear picture, so they can just pull out the phone ask people where is that bear!
> 
> You can pass this to intern if you are busy. Pretty good user-centered design exercise

**Comment by indirectlylit** [comment]
I don't think we have a 'directions' page anymore
