### ISSUE TITLE
Use scrollspy to update the side nav on giving and internships page 

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#32]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Tuesday Mar 11, 2014 at 23:21 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/53_

---

**Comment by indirectlylit** [comment]
no longer applicable
