### ISSUE TITLE
Browser Back-button fires-off another download

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#36]
<a href="https://github.com/bcipolli"><img src="https://avatars.githubusercontent.com/u/4072455?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcipolli](https://github.com/bcipolli)**
_Saturday Mar 29, 2014 at 15:03 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/65_

---

_Issue by **[gimick](https://github.com/gimick)** from Tuesday Nov 26, 2013 at 21:53 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/1145_

---

After landing on http://pi2:8001/download/wizard/single-server/ with the download complete, any navigation away and back again fires off another download.

Steps to recreate:
Download a zip file
Select another link (www.python.org , FAQ, Contact or whatever)
Select browser back button to return

Once the page returns, the download counter starts again..... 10...9....8 and I get another copy of the installer across the wire.

This is unexpected behavior.

**Comment by indirectlylit** [comment]
no longer applicable
