### ISSUE TITLE
UI for easy customization of a download package / installation options

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#39]
<a href="https://github.com/bcipolli"><img src="https://avatars.githubusercontent.com/u/4072455?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcipolli](https://github.com/bcipolli)**
_Thursday Apr 03, 2014 at 14:52 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/68_

---

_Issue by **[bcipolli](https://github.com/bcipolli)** from Tuesday Aug 27, 2013 at 18:21 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/589_

---

We've created a nice download page for easy zone-based installation.  However, we have no easy way to deploy customized setup--that's in the local_settings file, and that is edited locally only.

Let's create a UI for the download page, where people could click "customize", and have a table of features--feature name, value, and a blurb about what it is.  Anything that people fill in, we'll create the local_settings file for them.

I'm happy to do the back-end work for this; anybody interested in building the front-end?

Because we don't have this, I'm having to do some manual work-arounds to get things ready for the IDOC deployment.

**Comment by indirectlylit** [comment]
this is something we're continuing to think about re: kolibri and the modular build system. cc @rtibbles @aronasorman @jamalex
