### ISSUE TITLE
Modal for "Contact Us" does not work in Firefox: returns object result

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#41]
<a href="https://github.com/hqcasanova"><img src="https://avatars.githubusercontent.com/u/6626603?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hqcasanova](https://github.com/hqcasanova)**
_Sunday Apr 13, 2014 at 12:47 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/70_

---

For a quick and dirty patch, the script inside the `href` attrib needs to be wrapped in `void()`:

```
href="javascript:void($('#contactModal').modal('toggle'));
```

However, if you have control over the markup, the ideal solution would be to move the javascript code into a dynamically added onclick handler. Plus, that would allow for incremental design (in case JS is not enabled).

**Comment by indirectlylit** [comment]
no longer applicable
