### ISSUE TITLE
Blog defaults to 404 when no posts 

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#44]
<a href="https://github.com/dylanjbarth"><img src="https://avatars.githubusercontent.com/u/1319950?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dylanjbarth](https://github.com/dylanjbarth)**
_Thursday May 22, 2014 at 18:39 GMT_
_Originally opened as https://github.com/dylanjbarth/fle-site/issues/73_

---

We should only hit this in development, but it's still a bug and should be fixed for new devs who are getting into the repo (at some point) 

![image](https://cloud.githubusercontent.com/assets/1319950/3058424/5668332a-e1e0-11e3-8ba8-0f2184ac488c.png)

**Comment by indirectlylit** [comment]
now using a different system
