### ISSUE TITLE
Link on Hub homepage leads to outdated wiki page

### ISSUE THREAD

**Issue by jtamiace** [fle-internal/fle-home#66]
![hub](https://cloud.githubusercontent.com/assets/6668144/3837280/eed18c2a-1de9-11e4-80d0-0e7ef3fa8bda.JPG)

After login on the KA Lite Hub homepage, the link highlighted in red leads to this page: 

![old wiki](https://cloud.githubusercontent.com/assets/6668144/3837282/0ebceb38-1dea-11e4-98f1-ee82be36c6ce.JPG)

which I believe is not the most up to date wiki page.

**Comment by indirectlylit** [comment]
as far as I can tell, this is no longer an issue
