### ISSUE TITLE
Updated "Past Contributors" section to something less awk

### ISSUE THREAD

**Issue by dylanjbarth** [fle-internal/fle-home#75]
Currently we just insert "Former" before the title of the past contributor, which is weird, so I propose adding a beginning and ending date field to each team member model, so that we can put something like "Software Development Intern, Jan 2014 to April 2014" or something along those lines.

**Comment by indirectlylit** [comment]
current status:

![image](https://user-images.githubusercontent.com/2367265/32810940-20a0bed0-c952-11e7-8149-20747dc1e271.png)
