### ISSUE TITLE
Team Page -- Person Bio Modal doesn't pop up in Firefox

### ISSUE THREAD

**Issue by anuragkanungo** [fle-internal/fle-home#86]
Only Exists in Firefox, Works fine in Chrome.

On clicking a profile, it returns:

![screen shot 2015-01-07 at 12 24 28 am](https://cloud.githubusercontent.com/assets/4207886/5634141/9864b212-9603-11e4-981f-841f6e136686.png)

**Comment by aronasorman** [comment]
@jtamiace or @anuragkanungo can you try debugging this?

**Comment by anuragkanungo** [comment]
@aronasorman , Issue is still there, why it is closed?

**Comment by jtamiace** [comment]
@aronasorman the fix has been merged, but has the site been relaunched yet?

**Comment by aronasorman** [comment]
Ah yup. Will work with @jamalex to get this launched today.
